apiVersion: apps/v1
kind: Deployment
metadata: {name: secure-demo-api}
spec:
  replicas: 2
  selector: {matchLabels: {app: secure-demo-api}}
  template:
    metadata: {labels: {app: secure-demo-api}}
    spec:
      securityContext: {runAsNonRoot: true, seccompProfile: {type: RuntimeDefault}}
      containers:
        - name: api
          image: ghcr.io/OWNER/devsecops-pipeline:latest
          ports: [{name: http, containerPort: 8000}]
          securityContext: {allowPrivilegeEscalation: false, capabilities: {drop: [ALL]}, readOnlyRootFilesystem: true}
          readinessProbe: {httpGet: {path: /health, port: http}}
          resources: {requests: {cpu: 10m, memory: 32Mi}, limits: {cpu: 100m, memory: 64Mi}}
---
apiVersion: v1
kind: Service
metadata: {name: secure-demo-api}
spec:
  selector: {app: secure-demo-api}
  ports: [{port: 80, targetPort: http}]
